### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by smoebody** [eonlepapillon/grunt-connect-http-auth#3]
the npm package still requires grunt 0.4.1.
```
+-- UNMET PEER DEPENDENCY grunt@1.0.1
`-- grunt-connect-http-auth@0.1.2 

npm WARN grunt-connect-http-auth@0.1.2 requires a peer of grunt@~0.4.1 but none was installed.
```

 would you be so kind and update the dependencies?

thanks in advance

**Comment by eonlepapillon** [comment]
Goodmorning @smoebody,

I'm not actively support this package anymore. It's open source feel free to make changes and if you make a pull request I'm willing to merge it with the current source.

Kind regards
